fragment tocFields on TocItem {
  name
  playOrder
  sectionId
  hash
}

fragment tocRecursive on TocItem {
  ...tocFields
  children {
    ...tocFields
    children {
      ...tocFields
      children {
        ...tocFields
        children {
          ...tocFields
        }
      }
    }
  }
}
