#import './BookRecursiveElements.gql'

fragment BookPages on BookPageConnection {
  totalCount
  fromHistory
  fromLocation
  startPage
  lastProgress
  offset
  edges {
    cursor
    node {
      id
      meta {
        pageNo
        offset
      }
      elements {
        ...BookRecursiveElements
      }
    }
  }
}
