query Posts {
  posts (
    category: BLOG
    status: PUBLISHED
    visibility: PUBLIC
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      node {
        id
        objectId
        title
        createdAt
        updatedAt
        author {
          id
          slug
        }
        markdown
        category
      }
    }
  }
}
