#import './fragments/BookInfo.gql'
#import './fragments/BookRecursiveElements.gql'

query ReaderQuery(
    $bookId: ID!,
    $before: String,
    $after: String,
    $first: Int,
    $last: Int,
    $pageHeight: Int!,
    $width: Int!,
    $lineHeight: Float!,
    $fontSize: Float!, 
    $offset: Int,
    $fromHistory: Boolean
    $fromLocation: String
  ) {
  bookInfo: node(id: $bookId) {
    ...on Book {
      ...BookInfo
    }
  }
  viewer {
    readingProgress(bookId: $bookId) {
      percentage
    }
    bookPages(
      offset: $offset,
      pageHeight: $pageHeight,
      width: $width,
      lineHeight: $lineHeight,
      fontSize: $fontSize,
      bookId: $bookId,
      first: $first,
      last: $last,
      before: $before,
      after: $after,
      fromHistory: $fromHistory,
      fromLocation: $fromLocation
    ) {
      totalCount
      fromHistory
      fromLocation
      startPage
      offset
      edges {
        cursor
        node {
          meta {
            pageNo
            offset
          }
          elements {
            ...BookRecursiveElements
          }
        }
      }
    }
  }
}
