#import './fragments/BookInfo.gql'
#import './fragments/BookRecursiveToc.gql'
#import './fragments/BookPages.gql'

query ReaderInit(
    $bookId: ID!,
    $before: String,
    $after: String,
    $first: Int,
    $last: Int,
    $pageHeight: Int!,
    $width: Int!,
    $lineHeight: Float!,
    $fontSize: Float!, 
    $offset: Int,
    $fromHistory: Boolean
    $fromLocation: String
  ) {
  bookInfo: node(id: $bookId) {
    ...on Book {
      ...BookInfo
      toc {
        ...BookRecursiveToc
      }
    }
  }
  viewer {
    id
    bookPages(
      offset: $offset,
      pageHeight: $pageHeight,
      width: $width,
      lineHeight: $lineHeight,
      fontSize: $fontSize,
      bookId: $bookId,
      first: $first,
      last: $last,
      before: $before,
      after: $after,
      fromHistory: $fromHistory,
      fromLocation: $fromLocation
    ) {
      ...BookPages
    }
  }
}
